baseurl = "http://mampaey.herokuapp.com/"
languageCode = "de-de"
title = "Mamapaey Bar & Service Training"
theme = "landing-page-hugo"
[params]
  description = "Bar & Service Training right at your Venue"